
-- Insert cidade
INSERT INTO coronavirus.cidade (nome) VALUES ('São Paulo');
INSERT INTO coronavirus.cidade (nome) VALUES ('Buenos Aires');
INSERT INTO coronavirus.cidade (nome) VALUES ('Madrid');
INSERT INTO coronavirus.cidade (nome) VALUES ('Los Angeles');
INSERT INTO coronavirus.cidade (nome) VALUES ('Miami');
INSERT INTO coronavirus.cidade (nome) VALUES ('New York City');
INSERT INTO coronavirus.cidade (nome) VALUES ('Rio de Janeiro');
INSERT INTO coronavirus.cidade (nome) VALUES ('Roma');
INSERT INTO coronavirus.cidade (nome) VALUES ('Canberra');

-- Insert tempo
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (1, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (2, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (3, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (4, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (5, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (6, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (7, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (8, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (9, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (10, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (11, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (12, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (13, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (14, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (15, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (16, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (17, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (18, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (19, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (20, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (21, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (22, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (23, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (24, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (25, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (26, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (27, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (28, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (29, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (30, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (31, 1, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (1, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (2, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (3, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (4, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (5, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (6, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (7, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (8, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (9, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (10, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (11, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (12, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (13, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (14, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (15, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (16, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (17, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (18, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (19, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (20, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (21, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (22, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (23, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (24, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (25, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (26, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (27, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (28, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (29, 2, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (1, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (2, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (3, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (4, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (5, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (6, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (7, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (8, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (9, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (10, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (11, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (12, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (13, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (14, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (15, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (16, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (17, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (18, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (19, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (20, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (21, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (22, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (23, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (24, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (25, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (26, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (27, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (28, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (29, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (30, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (31, 3, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (1, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (2, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (3, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (4, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (5, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (6, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (7, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (8, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (9, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (10, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (11, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (12, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (13, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (14, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (15, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (16, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (17, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (18, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (19, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (20, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (21, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (22, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (23, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (24, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (25, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (26, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (27, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (28, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (29, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (30, 4, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (1, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (2, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (3, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (4, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (5, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (6, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (7, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (8, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (9, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (10, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (11, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (12, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (13, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (14, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (15, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (16, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (17, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (18, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (19, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (20, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (21, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (22, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (23, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (24, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (25, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (26, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (27, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (28, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (29, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (30, 5, 2020);
INSERT INTO coronavirus.tempo (dia, mes, ano) VALUES (31, 5, 2020);

-- Insert pais
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('BRA', 'Brazil', 209469333, 'America do Sul');
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('ARG', 'Argentina', 44494502, 'America do Sul');
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('AUS', 'Australia', 24992369, 'Oceania');
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('USA', 'United States of America', 327167434, 'America do Norte');
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('ESP', 'Spain', 46723749, 'Europa');
INSERT INTO coronavirus.pais (codigo_iso, nome, pop, continente) VALUES ('ITA', 'Italy', 60431283, 'Europa');

-- Insert leitos
INSERT INTO coronavirus.leitos (total_leitos, pais_iso) VALUES (32363, 'BRA');

-- Insert temperatura
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-15);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-14);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-13);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-12);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-11);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-10);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-9);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-8);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-7);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-6);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-5);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-4);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-3);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-2);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (-1);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (0);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (1);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (2);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (3);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (4);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (5);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (6);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (7);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (8);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (9);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (10);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (11);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (12);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (13);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (14);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (15);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (16);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (17);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (18);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (19);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (20);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (21);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (22);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (23);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (24);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (25);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (26);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (27);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (28);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (29);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (30);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (31);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (32);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (33);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (34);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (35);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (36);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (37);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (38);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (39);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (40);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (41);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (42);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (43);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (44);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (45);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (46);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (47);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (48);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (49);
INSERT INTO coronavirus.temperatura (temp_celsius) VALUES (50);